@BASE_URL = http://localhost:4004/odata/v4

### Lista Estudantes
GET {{BASE_URL}}/export-srv/GetEstudantes

### Filtra Estudante por email
GET {{BASE_URL}}/export-srv/GetEstudantes(email='joao.silva@example.com')

### Cria Estudante
POST {{BASE_URL}}/export-srv/UpdateEstudantes
Content-Type: application/json

{
  "first_name": "Joãozinho",
  "email": "joao.silva@example.com"
}